Add separator parameter
mstachniuk/ci-skip pull request #4
Opened 2020-11-18 15:03 UTC by GuillaumeFavelier

This PR adds a `separator` parameter to allow for multiple filters. With something like:

```
      - uses: GuillaumeFavelier/ci-skip@enh/separator
        with:
          commit-filter: '[skip ci];[ci skip];[skip github]'
          separator: ';'
```

2020-11-18 15:04 UTC, GuillaumeFavelier commented
What do you think @mstachniuk ?

2020-11-18 15:40 UTC, mstachniuk requested changes
Thank you for your PR. I like your idea because it's simple. I thought about using Regex instead, but then commit-filter will be hard to read.

Could you add some tests (see /test directory) and document use case in readme, please? After that I can merge your PR.

2020-11-18 15:40 UTC, mstachniuk commented on script.sh
> +  echo "The last commit log does not contains \"$commit_filter\", setting environment variables for next steps:"
good catch, thank you

2020-11-18 16:18 UTC, GuillaumeFavelier commented
Locally, I have an issue with my `docker`:

```
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon.
```

So I added 2 tests... blindly :sweat_smile: 
Also I'm not sure about the hash used: b5634847ae9760ee46cf8a1c928cd8689a821744 since the others are available on `master`

2020-11-19 14:31 UTC, GuillaumeFavelier commented
It's also possible to create a skip job instead of repeating `if: ${{ env.SKIP == 'false' }}`

```
jobs:
  check_skip:
    runs-on: ubuntu-20.04
    outputs:
      skip: ${{ steps.result_step.outputs.result }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: GuillaumeFavelier/ci-skip@enh/separator
        with:
          commit-filter: '[skip ci];[ci skip];[skip github]'
          separator: ';'
      - run: echo "::set-output name=result::${CI_SKIP}"
        id: result_step

  main_job:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
...
```

2020-11-19 15:59 UTC, mstachniuk commented
@GuillaumeFavelier I will merge your PR and fix tests and small things soon. I will also rename separator to `commit-filter-separator` - I have more ideas to implement and this rename helps me avoid misunderstandings.
Thanks a lot for submitting Pull Request!

2020-11-19 15:59 UTC, merged

2020-11-19 16:16 UTC, mstachniuk commented
Ok it's done.
Btw. An idea with skip job looks interesting. Would you add it to Readme and full working example in /.github/workflows ?

2020-11-20 13:49 UTC, GuillaumeFavelier commented
I'm ont it